# src/Acme/UserBundle/Resources/config/doctrine/Group.orm.yml
Xavierlis\UserBundle\Entity\Group:
    type:  entity
    table: xl_group
    id:
        id:
            type: integer
            generator:
                strategy: AUTO